import type { Metadata } from "next";

import "./globals.css";
import { GlobalStateProvider } from "@/contexts/GlobalProviderContext";
import Navbar from "@/components/section/Navbar";
import Footer from "@/components/section/Footer";

export const metadata: Metadata = {
  title: "Blogtivus",
  description: "Generated by create next app",
  icons: "/svg/blogtivus.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStateProvider>
          <Navbar />
          {children}
          <Footer />
        </GlobalStateProvider>
      </body>
    </html>
  );
}
